import { Base64 } from 'js-base64';

const PUBLICATION_URL = process.env.NEXT_PUBLICATION_URL;

const stripEmojis = (str: string) =>
	str
		.replace(
			/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g,
			'',
		)
		.replace(/\s+/g, ' ')
		.trim();

export const getAutogeneratedPostOG = (post: any, publication: any) => {
	const ogUrl = `${PUBLICATION_URL || publication.url}/api/og/post`;
	const ogData: any = {};

	try {
		ogData.title = encodeURIComponent(stripEmojis(post.title));
		ogData.author = encodeURIComponent(publication.author);
		ogData.domain = new URL(PUBLICATION_URL || publication.url).hostname;
		ogData.photo = "https://" + ogData.domain + "/" + publication.photo;
		// ogData.readTime = readTimeInMinutes;
	} catch (e) {
		console.log(e);
	}
	return `${ogUrl}?og=${Base64.encode(JSON.stringify(ogData))}`;
};

export const getAutogeneratedPublicationOG = (publication: any, posts: any) => {
	const totalDocuments = posts.length;

	const ogUrl = `${PUBLICATION_URL || publication.url}/api/og/home`;
	const ogData: Record<string, any> = {};

	try {
		ogData.title = publication.title;
		ogData.domain = new URL(PUBLICATION_URL || publication.url).hostname;
		ogData.followers = 0;

		ogData.photo = "https://" + ogData.domain + "/" + publication.photo;

		ogData.logo = "https://" + ogData.domain + "/" + publication.logo;

		ogData.isTeam = false;

		ogData.meta = encodeURIComponent(stripEmojis(publication.description)); // Vercel OG is not able to work with all kinds of emojis

		ogData.favicon = publication.favicon;

		if (totalDocuments && totalDocuments > 0) {
			ogData.articles = totalDocuments;
		}
	} catch (e) {
		console.log(e);
	}
	return `${ogUrl}?og=${Base64.encode(JSON.stringify(ogData))}`;
};
