import { resizeImage } from '@starter-kit/utils/image';
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
// @ts-ignore
import handleMathJax from '@starter-kit/utils/handle-math-jax';
import { useEmbeds } from '@starter-kit/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@starter-kit/utils/renderer/services/embed';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { CoverImage } from '../components/cover-image';
import { DateFormatter } from '../components/date-formatter';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import { PersonalHeader } from '../components/personal-theme-header';
// @ts-ignore
import { triggerCustomWidgetEmbed } from '@starter-kit/utils/trigger-custom-widget-embed';
import { getPosts } from '../utils/posts';
import { Post } from '../utils/post';
import { getPublication } from '../utils/publication';

type PostProps = {
	type: 'post';
	post: Post;
};

const PostPage = ({ post }: PostProps) => {
	const publication = getPublication();

	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';
	const [, setMobMount] = useState(false);
	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	useEmbeds({ enabled: canLoadEmbeds });

	// if (post.hasLatexInPost) {
	// 	setTimeout(() => {
	// 		handleMathJax(true);
	// 	}, 500);
	// }

	useEffect(() => {
		if (screen.width <= 425) {
			setMobMount(true);
		}

		if (!post) {
			return;
		}

		// TODO:
		// More of an alert, did this below to wrap async funcs inside useEffect
		(async () => {
			await loadIframeResizer();
			// triggerCustomWidgetEmbed(post.publication?.id.toString());
			setCanLoadEmbeds(true);
		})();
	}, []);

	// const coverImageSrc = !!post.coverImage?.url
	// 	? resizeImage(post.coverImage.url, {
	// 			w: 1600,
	// 			h: 840,
	// 			c: 'thumb',
	// 	  })
	// 	: undefined;

	return (
		<>
			<Head>
				<title>{post.title}</title>
				{/* <meta name="description" content={post.seo?.description || post.subtitle || post.brief} /> */}
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.title} />
				{/* <meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/> */}
				<meta
					property="og:image"
					content={
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>
			<h1 className="text-4xl font-bold leading-tight tracking-tight text-black dark:text-white">
				{post.title}
			</h1>
			<div className="flex tracking-tight gap-2 text-neutral-600 dark:text-neutral-400">
				<DateFormatter dateString={post.datePublished} />
				{'•'}
				<span>{Math.ceil((post.content?.split(" ").length || 0) / 200)} minute read</span>
			</div>
			{/* {!!coverImageSrc && (
				<div className="w-full">
					<CoverImage title={post.title} priority={true} src={coverImageSrc} />
				</div>
			)} */}
			<MarkdownToHtml contentMarkdown={post.content || ""} />
		</>
	);
};

export default function PostOrPage(props: PostProps) {
	return (
		<AppProvider post={props.post}>
			<Layout>
				<Container className="mx-auto flex max-w-3xl flex-col items-stretch gap-10 px-5 py-10">
					<PersonalHeader />
					<article className="flex flex-col items-start gap-10 pb-10">
						{props.type === 'post' && <PostPage {...props} />}
					</article>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<PostProps, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}

	const slug = params.slug;

	if (!/^[a-z0-9-]+$/.test(slug)) {
		return {
			notFound: true,
			revalidate: 300,
		};
	}

	const data = getPosts();
	const postData = data.find(post => post.slug == slug);

	if (postData) {
		return {
			props: {
				type: 'post',
				post: postData,
			},
			revalidate: 300,
		};
	}

	return {
		notFound: true,
		revalidate: 300,
	};
};

export async function getStaticPaths() {
	const data = getPosts();

	const postSlugs = data.map(post => post.slug)

	return {
		paths: postSlugs.map((slug) => {
			return {
				params: {
					slug: slug,
				},
			};
		}),
		fallback: 'blocking',
	};
}
