import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import { Newsletter } from '../components/newsletter';
import { getPosts } from '../utils/posts';
import { getPublication } from '../utils/publication';
import { Post } from '../utils/post';

type Props = {
	posts: Post[];
};

export default function Index({ posts }: Props) {
	const publication = getPublication();
	return (
		<AppProvider>
			<Layout>
				<Head>
					<title>{publication.title}</title>
					<meta
						name="description"
						content={publication.description}
					/>
					<meta property="twitter:card" content="summary_large_image"/>
					<meta property="twitter:title" content={publication.title} />
					<meta property="twitter:description" content={publication.description} />
					<meta
						property="og:image"
						content={getAutogeneratedPublicationOG(publication, posts)}
					/>
					<meta
						property="twitter:image"
						content={getAutogeneratedPublicationOG(publication, posts)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Container className="mx-auto flex max-w-3xl w-full flex-col items-stretch gap-10 px-5 py-10">
					<PersonalHeader />
					<p>
						{publication.description}
					</p>
					{posts.length > 0 && <MinimalPosts context="home" posts={posts} />}
					<Newsletter />
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {

	try {
		const posts = await getPosts();
		return {
			props: {
				posts
			},
			revalidate: 300,
		};
	} catch {
		return {
			notFound: true,
			revalidate: 1,
		};
	}
};
